name: CI

# We can specify which Github events will trigger a CI build
on:
  push:
    branches:
      - main  # Adjust the branch name as needed

# Define a single job 'build'
jobs:
  build:
    # Specify the OS to run tests on
    runs-on: ubuntu-latest

    # Define a sequence of steps
    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3  # Updated to use Node.js 20

      # Set up Python 3.11
      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"

      # Install Python dependencies
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      # Test with PyTest
      - name: Test with PyTest
        run: |
          python -m pytest --cov=catchment.models tests/test_models.py
